server:
    port: 10010


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


spring:
    application:
        name: order-service
    redis:
#        host: 192.168.64.129  #测试
        host: 127.0.0.1
        #    host: 172.16.215.49  #生产
        timeout: 2000
        port: 6379
        database: 0
#        password: 1313008hardtl

ec-commerce-commodity-service:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
    hystrix:
        enabled: true
    client:
        config:
            default:
                connectTimeout: 2000
                readTimeout: 3000

#hystrix 熔断超时时间
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 4000

logging:
    level:
        org.springframework.web: TRACE