server:
    port: 10010


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


spring:
    application:
        name: order-service

ec-commerce-commodity-service:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
    client:
        config:
            default:
                connectTimeout: 2000
                readTimeout: 3000

