server:
    port: 10010


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


spring:
    application:
        name: order-service
    redis:
#        host: 192.168.64.129  #测试
        host: 120.79.18.7
        #    host: 172.16.215.49  #生产
        timeout: 2000
        port: 16379
        password: chenrenshui
        database: 0
#        password: 1313008hardtl

ec-commerce-commodity-service:
    ribbon:
        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
    hystrix:
        enabled: true
    client:
        config:
            default:
                connectTimeout: 2000
                readTimeout: 3000

